on: 
  push:
    branches:
      - main

name: Deploy website on push

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Deploy no servidor Amplar
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.ftp_host_amplar }}
        username: ${{ secrets.ftp_user_amplar }}
        password: ${{ secrets.ftp_password_amplar }}
        server-dir: lp.amplargs.com.br/